// Centralized icon imports to prevent Vite chunking issues
export {
  IconChevronDown,
  IconChevronUp,
  IconX,
  IconVolume,
  IconHeart,
  IconHeartFilled,
  IconCircleX,
  IconPlayerPlay,
  IconPlayerPause,
  IconPlayerSkipBack,
  IconPlayerSkipForward,
  IconMusic,
  IconUser,
  IconExternalLink,
  IconMicrophone,
  IconStar,
  IconCheck,
  IconAlertCircle,
  IconInfoCircle,
  IconUsers,
  IconUserPlus,
  IconMail,
  IconLock,
  IconSearch,
  IconDots,
} from '@tabler/icons-react'
