name: Claude Code Review (Basic)

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  claude-review:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        id: lint
        continue-on-error: true
        run: npm run lint

      - name: Run tests  
        id: test
        continue-on-error: true
        run: npm run test

      - name: Get PR diff
        if: github.event.issue.pull_request
        id: diff
        run: |
          PR_NUMBER=$(echo "${{ github.event.issue.number }}")
          gh pr diff $PR_NUMBER > pr-diff.txt || echo "Could not get diff"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare review context
        id: context
        run: |
          echo "Creating review context..."
          echo "## PR Context" > review-context.md
          echo "- Lint status: ${{ steps.lint.outcome }}" >> review-context.md  
          echo "- Test status: ${{ steps.test.outcome }}" >> review-context.md
          echo "- Comment: ${{ github.event.comment.body }}" >> review-context.md

      - name: Call Claude API
        run: |
          cat > claude-request.json << 'EOF'
          {
            "model": "claude-3-5-sonnet-20241022",
            "max_tokens": 1000,
            "messages": [
              {
                "role": "user", 
                "content": "Please review this pull request. Here's the context:\n\n$(cat review-context.md)\n\nUser request: ${{ github.event.comment.body }}\n\nProject guidelines are in CLAUDE.md. Please provide a helpful code review response."
              }
            ]
          }
          EOF

          RESPONSE=$(curl -s -X POST https://api.anthropic.com/v1/messages \
            -H "Content-Type: application/json" \
            -H "x-api-key: ${{ secrets.ANTHROPIC_API_KEY }}" \
            -H "anthropic-version: 2023-06-01" \
            -d @claude-request.json)
          
          REVIEW_TEXT=$(echo "$RESPONSE" | jq -r '.content[0].text // "Error getting response"')
          
          gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -f body="$REVIEW_TEXT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}